version: '3.9'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:7-alpine
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  discountdb:
    image: postgres:15
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discountdatadb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050


  eshopcatalogapi:
    image: fansoft/eshopcatalogapi
    container_name: eshop.catalog.api
    build:
      context: .
      dockerfile: EShop.Catalog.Api/Dockerfile
    ports:
      - 8081:80
    environment:
      - ASPNET_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__CollectionName=Products
    depends_on:
      - catalogdb

  eshopbasketgapi:
    image: fansoft/eshopbasketapi
    container_name: eshop.basket.api
    build:
      context: .
      dockerfile: EShop.Basket.Api/Dockerfile
    ports:
      - 8082:80
    environment:
      - ASPNET_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379
    depends_on:
      - basketdb

  eshopdiscountapi:
    image: fansoft/eshopdiscountapi
    container_name: eshop.discount.api
    build:
      context: .
      dockerfile: EShop.Discount.Api/Dockerfile
    ports:
      - 8083:80
    environment:
      - ASPNET_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConn=Server=discountdb;Port=5432;Database=discountdatadb;User Id=admin;Password=admin1234
    depends_on:
      - discountdb

volumes:
  mongo_data:
  postgres_data:
